name: ci
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go environment
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
    - name: Run
      run: make test
